spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=SangECommerce;encrypt=true;trustServerCertificate=true;
    username: SA
    password: StrongPassword123!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
  hikari:
    maximum-pool-size: 10

